name: Publish Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@ashish-r'

      - name: Insert repository owner as scope into package name
        run: |
          node <<EOF
          const fs = require('fs').promises;
          fs.readFile('package.json', 'utf8').then((data) => JSON.parse(data)).then((json) => {
              json.name = '@$(echo "$GITHUB_REPOSITORY" | sed 's/\/.\+//')/' + json.name;
              console.info('Package name changed to %s', json.name);
              return fs.writeFile('package.json', JSON.stringify(json), 'utf8');
          }).catch(error => {
              console.error(error);
              process.exit(1);
          });
          EOF
      - run: npm ci
      - run: echo registry=https://npm.pkg.github.com/@ashish-r >> .npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_GITHUB_TOKEN}}